from fpdf import FPDF
import datetime
import os

class ReportGenerator:
    """
    Step 5.6 - PDF Final Report Generation
    Generates a professional executive summary of the interview performance.
    """
    def __init__(self, output_dir="reports"):
        self.output_dir = output_dir
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)

    def generate_candidate_report(self, candidate_name, score_data, feedback_logs):
        pdf = FPDF()
        pdf.add_page()
        
        # Header
        pdf.set_font("Arial", 'B', 24)
        pdf.set_text_color(40, 40, 150)
        pdf.cell(0, 20, "AI Interview Assessment Report", ln=True, align='C')
        
        pdf.set_font("Arial", '', 12)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 10, f"Generated on: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True, align='C')
        pdf.ln(10)
        
        # Candidate Info
        pdf.set_font("Arial", 'B', 16)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, f"Candidate: {candidate_name}", ln=True)
        pdf.set_draw_color(40, 40, 150)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(10)
        
        # Performance Summary
        pdf.set_font("Arial", 'B', 14)
        pdf.cell(0, 10, "1. Executive Summary", ln=True)
        pdf.set_font("Arial", '', 12)
        
        total_score = score_data.get("total_score", 0)
        pdf.cell(0, 10, f"Overall Performance Score: {total_score}/10", ln=True)
        
        breakdown = score_data.get("breakdown", {})
        pdf.cell(0, 10, f"- Answer Quality: {breakdown.get('answer_quality', 0)}/10", ln=True)
        pdf.cell(0, 10, f"- Professional Behavior: {breakdown.get('behavior', 0)}/10", ln=True)
        pdf.cell(0, 10, f"- Cheating Risk: {breakdown.get('cheating_risk', 'Unknown')}", ln=True)
        pdf.ln(5)
        
        # Detailed Feedback
        pdf.set_font("Arial", 'B', 14)
        pdf.cell(0, 10, "2. Detailed Question Breakdown", ln=True)
        pdf.set_font("Arial", '', 11)
        
        for log in feedback_logs:
            pdf.multi_cell(0, 8, f"• {log}")
        
        pdf.ln(10)
        
        # Footer
        pdf.set_y(-30)
        pdf.set_font("Arial", 'I', 8)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 10, "This report is generated by the AI Autonomous Interview System. All scores are based on NLP and Computer Vision analytics.", align='C')

        filename = f"Report_{candidate_name.replace(' ', '_')}_{datetime.datetime.now().strftime('%Y%m%d%H%M')}.pdf"
        filepath = os.path.join(self.output_dir, filename)
        pdf.output(filepath)
        return filepath

# Singleton instance
report_generator = ReportGenerator()
